spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        log-in-0:
          destination: log-exchange
          group: log-queue
        log-out-0:
          destination: log-exchange
          group: log-queue
